version: '3.1'
services :
  cloudserver:
    image: zenko/cloudserver
    restart: always
    ports:
      - "8123:8000"
    environment:
      REMOTE_MANAGEMENT_DISABLE: 1
    volumes:
      - ~/.local-s3/localData:/usr/src/app/localData
      - ~/.local-s3/localMetadata:/usr/src/app/localMetadata
